### ISSUE TITLE
VM hangs at usbhid: USB HID core driver

### ISSUE THREAD

**Issue by m0stlyharmless** [robotpy/roborio-vm#2]
Hello,

After setting up the VM using FRC_roboRIO_2017_v8.zip and launching it, it hangs at usbhid: USB HID core driver and uses up the entirety of one of my CPU cores. I have attempted creating the VM on two computers (one running Fedora 25 x86_64 and the other running Debian 8 x86_64) and the issue is present on both of them. What could be the source of this issue?

Thanks.

**Comment by virtuald** [comment]
Which version of QEMU are you using, and did you compile from source or did you install the one that came with your distro?

I've had good success with QEMU 2.6 on Fedora 24, 2.8 freezes for me.

**Comment by m0stlyharmless** [comment]
I am running QEMU 2.7.1. I installed it using the package manager.

**Comment by auscompgeek** [comment]
FWIW, the VM works fine for me on QEMU 2.8 on Arch Linux.

**Comment by virtuald** [comment]
Hm. Looking at my README notes, it appears that 2.7 was the one that didn't work for me at all. 2.8 works, but freezes occasionally. 2.6 is pretty good. It's not too hard to build QEMU from source, I would recommend doing that.

**Comment by m0stlyharmless** [comment]
I have followed the instructions here (https://fedoraproject.org/wiki/Virtualization_Preview_Repository) to install a newer version of QEMU (version 2.8.92). This solved the issue with it hanging.

Thank you for your help.

**Comment by virtuald** [comment]
Awesome!
